version: '2.4'
services:
  postgres:
    image: postgres:15.1
    container_name: todolist-postgres

    logging:
      driver: json-file
      options:
        max-size: '100m'
        max-file: '5'

    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=

  todo_list:
    build:
      context: .
    image: todo_list:latest
    container_name: todo_list
    hostname: todo_list
    environment:
      - TOKEN=
      - DBNAME=
      - PASSWORD=
      - HOST=
      - USER=
      - PORT=

